// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFI0H83-po8BQnReg9ynsf2aZR6fmuFVQ',
    appId: '1:1069721041175:web:9dc71e827a549a01e5df52',
    messagingSenderId: '1069721041175',
    projectId: 'ecommerce-6e49c',
    authDomain: 'ecommerce-6e49c.firebaseapp.com',
    databaseURL: 'https://ecommerce-6e49c-default-rtdb.firebaseio.com',
    storageBucket: 'ecommerce-6e49c.firebasestorage.app',
    measurementId: 'G-ECCGW2524G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1TwnZ3Jg4HNzz9dRIgjcLtGwjybF4afQ',
    appId: '1:1069721041175:android:21fb8803f9f5cee4e5df52',
    messagingSenderId: '1069721041175',
    projectId: 'ecommerce-6e49c',
    databaseURL: 'https://ecommerce-6e49c-default-rtdb.firebaseio.com',
    storageBucket: 'ecommerce-6e49c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTkYP4BvHaDPlAboMdpxrX4xJ8U_cmmLQ',
    appId: '1:1069721041175:ios:9b1b27a92505185fe5df52',
    messagingSenderId: '1069721041175',
    projectId: 'ecommerce-6e49c',
    databaseURL: 'https://ecommerce-6e49c-default-rtdb.firebaseio.com',
    storageBucket: 'ecommerce-6e49c.firebasestorage.app',
    iosBundleId: 'com.example.flutterEcommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCTkYP4BvHaDPlAboMdpxrX4xJ8U_cmmLQ',
    appId: '1:1069721041175:ios:9b1b27a92505185fe5df52',
    messagingSenderId: '1069721041175',
    projectId: 'ecommerce-6e49c',
    databaseURL: 'https://ecommerce-6e49c-default-rtdb.firebaseio.com',
    storageBucket: 'ecommerce-6e49c.firebasestorage.app',
    iosBundleId: 'com.example.flutterEcommerceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBFI0H83-po8BQnReg9ynsf2aZR6fmuFVQ',
    appId: '1:1069721041175:web:8386eb8e92e606c8e5df52',
    messagingSenderId: '1069721041175',
    projectId: 'ecommerce-6e49c',
    authDomain: 'ecommerce-6e49c.firebaseapp.com',
    databaseURL: 'https://ecommerce-6e49c-default-rtdb.firebaseio.com',
    storageBucket: 'ecommerce-6e49c.firebasestorage.app',
    measurementId: 'G-1XEE63B7V9',
  );
}
